baseURL = "https://paranormaldistributions.com/"
languageCode = "en-us"
title = "Paranormal Distributions"
paginate = 10
enableRobotsTXT = true

[params]
  description = "I find patterns in places they shouldn't exist. Business Analyst at Swiggy by day, chasing paranormal distributions by night."
  author = "Jithin K Haridas"
  github = "https://github.com/jithinharidas"
  linkedin = "https://www.linkedin.com/in/jithinharidas"
  email = "jithinharidas8@gmail.com"

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
  [markup.goldmark.renderer]
    unsafe = true
publishDir = "docs"
